INSERT INTO products (
  id, slug, name, description, analysis_query, aliases_json, source_config_json,
  is_active, next_analysis_at, created_at, updated_at
) VALUES
('prod-new-outlook', 'new-outlook', 'New Outlook', 'The new Outlook for Windows and its transition from classic Outlook.', '"new Outlook" Microsoft OR "Outlook for Windows" -classic', '["new Outlook for Windows","Outlook new client"]', '{"subreddits":["Outlook","Microsoft365","sysadmin"]}', 1, datetime('now', '+1 day'), datetime('now'), datetime('now')),
('prod-m365-copilot', 'microsoft-365-copilot', 'Microsoft 365 Copilot', 'Microsoft 365 Copilot across Word, Excel, PowerPoint, Outlook, and Teams.', '"Microsoft 365 Copilot" OR "M365 Copilot"', '["M365 Copilot","Copilot for Microsoft 365"]', '{"subreddits":["Microsoft365","microsoft","sysadmin"]}', 1, datetime('now', '+1 day'), datetime('now'), datetime('now')),
('prod-copilot-chat', 'copilot-chat', 'Copilot Chat', 'Microsoft 365 Copilot Chat for work.', '"Microsoft 365 Copilot Chat" OR "Copilot Chat" Microsoft', '["Microsoft 365 Copilot Chat","M365 Copilot Chat"]', '{"subreddits":["Microsoft365","microsoft"]}', 1, datetime('now', '+2 day'), datetime('now'), datetime('now')),
('prod-teams-premium', 'teams-premium', 'Teams Premium', 'Premium Microsoft Teams meetings and event capabilities.', '"Teams Premium" Microsoft', '["Microsoft Teams Premium"]', '{"subreddits":["MicrosoftTeams","Microsoft365"]}', 1, datetime('now', '+2 day'), datetime('now'), datetime('now')),
('prod-teams-phone', 'teams-phone', 'Teams Phone', 'Microsoft Teams cloud calling and PSTN capabilities.', '"Teams Phone" Microsoft OR "Teams Calling"', '["Microsoft Teams Phone","Teams Calling"]', '{"subreddits":["MicrosoftTeams","VOIP"]}', 1, datetime('now', '+3 day'), datetime('now'), datetime('now')),
('prod-loop', 'microsoft-loop', 'Microsoft Loop', 'Microsoft Loop collaborative workspaces and components.', '"Microsoft Loop" app OR "Loop components" Microsoft', '["Loop components","Microsoft Loop app"]', '{"subreddits":["MicrosoftLoop","Microsoft365"]}', 1, datetime('now', '+3 day'), datetime('now'), datetime('now')),
('prod-planner', 'microsoft-planner', 'Microsoft Planner', 'The new Microsoft Planner and task management experience.', '"Microsoft Planner" OR "new Planner" Microsoft', '["new Microsoft Planner","Planner app"]', '{"subreddits":["Microsoft365","MicrosoftTeams"]}', 1, datetime('now', '+4 day'), datetime('now'), datetime('now')),
('prod-lists', 'microsoft-lists', 'Microsoft Lists', 'Microsoft Lists information tracking product.', '"Microsoft Lists" app OR "Lists in Teams"', '["Lists in Teams","Microsoft Lists app"]', '{"subreddits":["MicrosoftLists","Microsoft365"]}', 1, datetime('now', '+4 day'), datetime('now'), datetime('now')),
('prod-sharepoint-agents', 'sharepoint-agents', 'SharePoint Agents', 'AI agents grounded in SharePoint sites and content.', '"SharePoint agents" OR "agents in SharePoint"', '["agents in SharePoint"]', '{"subreddits":["sharepoint","Microsoft365"]}', 1, datetime('now', '+5 day'), datetime('now'), datetime('now')),
('prod-intune', 'microsoft-intune', 'Microsoft Intune', 'Microsoft cloud endpoint management and security.', '"Microsoft Intune" OR "Intune Suite"', '["Intune","Intune Suite"]', '{"subreddits":["Intune","sysadmin"]}', 1, datetime('now', '+5 day'), datetime('now'), datetime('now')),
('prod-entra', 'microsoft-entra', 'Microsoft Entra', 'Microsoft identity and network access product family.', '"Microsoft Entra" OR "Entra ID" Microsoft', '["Entra ID","Microsoft Entra ID"]', '{"subreddits":["entra","AzureActiveDirectory","sysadmin"]}', 1, datetime('now', '+6 day'), datetime('now'), datetime('now'));
